on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Would you like to delete these resources?"
        required: true
        type: choice
        options:
          - "yes"
          - "no"
jobs:
  delete:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      name: "Repository Checkout"
      uses: actions/checkout@v3

      name: "Setting up terraform"
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: 1.9.8

      name: "terraform initialisation"
      run: terraform init
      working_directory: ../terraform/

      if: ${{github.event.inputs.confirm_destroy == 'yes'}}
      name: "terraform destroy"
      run: terraform destroy -auto-approve
      working_directory: ../terraform/

      
