on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Would you like to delete these resources?"
        required: true
        type: choice
        options:
          - "yes"
          - "no"

jobs:
  delete:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: "Repository Checkout"
        uses: actions/checkout@v3

      - name: "Setting Up Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: "Terraform Initialization"
        run: terraform init
        working-directory: ./terraform/

      - name: "Terraform Destroy"
        if: ${{ github.event.inputs.confirm_destroy == 'yes' }}
        run: terraform destroy -auto-approve
        working-directory: ./terraform/

